using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using Component.TheHunters;
using Component.TheHunters.Enumerations;
using Component.TheHunters.IO;
using Component.TheHunters.Models.Charts;

namespace JsonWriterConsole.Creators
{
    /// <summary>
    /// <see cref="IConfigurationFileCreator"/>
    /// <para>This class creates configuration files for ship lists.</para>
    /// </summary>
    internal class ShipListCreator : IConfigurationFileCreator
    {
        /// <summary>
        /// <see cref="IConfigurationFileCreator.WriteData(string)"/>
        /// </summary>
        public void WriteData(string configFileFolder)
        {
            var data = BuildData();
            WriteShipListsToJson(configFileFolder, data);
        }

        #region METHODS
        private static void WriteShipListsToJson(string configFileFolder, IDictionary<string, IList<Ship>> data)
        {
            foreach (var shipList in data)
            {
                using var fileStream = new FileStream(Path.Combine(configFileFolder, "Ships", shipList.Key + ".json"), FileMode.Create);
                using var utf8JsonWriter = new Utf8JsonWriter(fileStream);
                JsonSerializer.Serialize<IList<Ship>>(utf8JsonWriter, shipList.Value);
            }
        }

        private static IDictionary<string, IList<Ship>> BuildData()
        {
            var shipLists = new Dictionary<string, IList<Ship>>
            {
                ["CapitalShips"] = CapitalShips(),
                ["Tankers"] = Tankers(),
                ["NorthAmerica.Tankers"] = NorthAmericaTankers(),
                ["SmallFreighters"] = SmallFreighters(),
                ["Optional.SmallFreighters"] = OptionalSmallFreighters(),
                ["NorthAmerica.SmallFreighters"] = NorthAmericaSmallFreighters(),
                ["LargeFreighters"] = LargeFreighters(),
                ["Optional.LargeFreighters"] = OptionalLargeFreighters(),
                ["NorthAmerica.LargeFreighters"] = NorthAmericaFreighters()
            };
            return shipLists;
        }
        private static IList<Ship> NorthAmericaFreighters()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8000, "Lady Hawkins", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8000, "Venore", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5700, "West Ivis", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Friar Rock", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9600, "Gandia", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8000, "TacomaStar", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 15400, "Amerikaland", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Lihue", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7900, "Arabutan", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Caryu", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8300, "City of New York", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 11000, "Hertford", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Nicoya", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Greylock", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Kronprinsen", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7100, "Qu'Appelle", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6200, "Peisander", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9000, "Westmoreland", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6800, "Alcoa Puritan", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "George Calvert", ShipRegion.NORTH_AMERICA) }
            };
        }

        private static IList<Ship> OptionalLargeFreighters()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7300, "El Oso", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6600, "Clan MacPhee", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5700, "Venetia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Empire Dew", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10500, "Danmark", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "Empire Merlin", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Hylton", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "St. Lindsay", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9500, "Inverdarge", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 15400, "Volendam", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6700, "Koranton", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Auditor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7800, "Caroni River", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Empire Adventure", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10000, "Beaverdale", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Botwey", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Keramiai", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Samala", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Welcombe", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6900, "Shahristan", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Chagres", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "Empire Ocelot", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6600, "Saleier", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Sauger", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Tiberton", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Benlawers", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8600, "Empire Endurance", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10300, "Otaio", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7400, "Pyrrhus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8400, "Port Gisborne", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Surat", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5600, "Empire Springbuck", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6700, "Pacific Reliance", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6900, "Pacific Ranger", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5700, "Eastern Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Muneric", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6200, "Eulota", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Shirac", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8300, "Piako", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Empire Crossbill", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Erik Frisell", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8200, "Caprella", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Cockaponset", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Evros", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "Orangemoor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Loch lomond", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Rothermere", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Empire Heron", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "Mount Nymettus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Planter", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6600, "Berhala", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Peru", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 13200, "Wellington Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Lady Glanely", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7400, "Helenus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Hellen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "Bamoralwood", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Empire Statesman", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Tabaristan", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Star of Luxor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Windsorwood", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9500, "Calabria", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7300, "Empire Storm", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6600, "Empire Surf", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 13400, "Avelona Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6600, "Alnmoor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6400, "Silveryew", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Harmatris", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 15500, "Arandora Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8500, "Siamese Prince", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Rinda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Caledonian Monarch", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "Humber Arm", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5700, "Empire Blanda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Gand", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5600, "Empire Wildebeeste", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8700, "Manipur", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Sirikishna", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5800, "City of Shanghai", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Empire Hall", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9300, "Accra", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6500, "Effna", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Harpagus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Benmohr", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Sambre", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Pacific", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7600, "Michael E.", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Baluchistan", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 13200, "Auckland Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8000, "Nardana", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Trecarrell", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5600, "Thursobank", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Jersey City", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Tielbank", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6400, "Silverpalm", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Induna", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "Geraldine Mary", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7400, "J.B. White", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5600, "Phidias", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Harpalion", ShipRegion.WORLD) }
            };
        }

        private static IList<Ship> LargeFreighters()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 12300, "Sultan Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Moh. Ali-Kebir", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7600, "Kingston Hill", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6200, "Fairport", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "SS Browning", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Ville de Mons", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 11000, "Norfolk", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5600, "Seattle Spirit", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "Manaar", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9000, "Titan", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Brockley Hill", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8400, "Port Nicholson", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Fanad Head", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Neptunian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Grayburn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7100, "Santore", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "Kennebec", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Jose de Larrinaga", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Anselm", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Cherokee", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Louisiane", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 11100, "City of Benares", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 11300, "Abosso", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "West Notus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9200, "Lochavon", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6900, "Corrientes", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Harlingen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Polyphemus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10000, "Bretagne", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9300, "Hurunui", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Empire Hudson", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6800, "Berganger", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Vermont", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 42300, "Empress of Britain", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Empire Wave", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Raphael Semmes", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "City of Mandalay", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Balzac", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9500, "Vancouver Island", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "City of Birmingham", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10000, "Yorkshire", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Matina", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6700, "Treverbyn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6800, "Moldanger", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "Clan Chisholm", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 18700, "Laurentic", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "King Malcolm", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8600, "Surrey", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8000, "Malabar", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Ville d' Arlon", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8500, "Nottingham", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Port Montreal", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Bronte", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10900, "Rotorua", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5300, "Silverbelle", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8400, "Santa Rita", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9900, "Beaverburn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10100, "Napier Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Sagadahoc", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "Alexander Macomb", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Rothesay Castle", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6000, "Empire Thunder", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5600, "Thornliebank", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8300, "Chilore", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6300, "Gustaf E. Reuter", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10600, "Zealandic", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 14600, "Ulysses", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "William C Bryant", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8800, "Navasota", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Ville d' Liege", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 12000, "Uangibbey Castle", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8100, "Umtata", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6700, "Brandon", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5400, "Athenic", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Buarque", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "Thomas McKean", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8200, "Tajandoen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10300, "Calchas", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7000, "Empire Howard", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Robert E. Lee", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5100, "Royston Grange", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10100, "Beacon Grange", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6900, "Empire Comet", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6400, "Triglav", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Cedarbank", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8900, "PortHardy", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10000, "Jagersfontein", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6400, "Peiping", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 9600, "Protesilaus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10300, "Ixion", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 6700, "Parnahyba", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7500, "Empire Tide", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 10500, "Brazza", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5900, "Gregalia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5700, "Steel Engineer", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 7200, "William Hooper", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5200, "Clearton", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 11800, "Rodney Star", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 8000, "Scottsburg", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.LARGE_FREIGHTER, 5500, "River Afton", ShipRegion.WORLD) }
            };
        }

        private static IList<Ship> NorthAmericaSmallFreighters()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3800, "Ciltvaira", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2300, "Norvana", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1600, "Frisco", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2600, "Frances Salman", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Ocean Venture", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2400, "Orangestad", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1100, "Acacia", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1900, "Tolten", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3400, "Esparta", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Christina Knudsen", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1000, "Cythera", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Reinheit", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1300, "Taborfjell", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3500, "Delisle", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Leto", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2100, "Skotttand", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Plow City", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Margot", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Zurichmoor", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2700, "Norlindo", ShipRegion.NORTH_AMERICA) }
            };
        }

        private static IList<Ship> OptionalSmallFreighters()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3800, "Alsacien", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Confield", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4200, "Homelea", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1300, "Lapland", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1300, "Quiberon", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3700, "Carsbreck", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Hindpool", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Belgravian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1300, "Miranda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Fiscus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4000, "Jhelum", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Aguila", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1600, "Gothia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4200, "Blairspey", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Medjerda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Embassage", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Vaclite", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3400, "Canford Chine", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Eastlea", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Tremoda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Munster", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Kayeson", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3800, "Umona", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Berury", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Maryland", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Ruperra", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Alderpool", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Jedmoor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Tara", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Uganda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Helena Margareta", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Lafian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Stancliffe", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Whitford Point", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2600, "Henri Mory", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "John Holt", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Swalnby", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Fabian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "WrayCastte", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3900, "Gypsum Queen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3600, "Polycarp", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Justitia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Queen Maud", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Baron Kelvin", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3900, "Aytesbury", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1900, "Irene Maria", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Oakdene", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Rose Schiaffino", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Pearlmoor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "St. Elwyn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1500, "Samso", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Bradford City", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Gogovate", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1600, "Palmella", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Vulcain", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3900, "Larpool", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Llanfair", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2800, "Kavak", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Eibergen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2000, "Flynderborg", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2300, "Betty", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2500, "Jeanne M.", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3200, "Baron Nairn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Gretavate", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "MillHIII", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Victoria City", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2900, "Robert Hughes", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4000, "Fjord", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2500, "HarZion", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3400, "Maplecourt", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Elmdene", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Grethead", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Bibury", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2700, "Dione II", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Yselhaven", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Shuntien", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2500, "Albionic", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2000, "Estrellano", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1500, "Havtor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2900, "Ruckinge", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Blairangus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Nailsea Lass", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2300, "Arakaka", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4000, "Traveller", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Alexandras", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4300, "Waynegate", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Ellinico", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4100, "Rio Blanco", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2500, "Heminge", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3800, "Cape Nelson", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2500, "Toronto City", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3800, "Modesta", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4100, "Darcoila", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3400, "Unaria", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Inverness", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2300, "Fred W. Green", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Ashantian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Jonathan Holt", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3400, "Holmside", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2600, "Montenol", ShipRegion.WORLD) }
            };
        }

        private static IList<Ship> SmallFreighters()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1800, "Bosnia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3600, "Aenos", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3500, "Baron Pentland", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2600, "City of Oxford", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4100, "RioClaro", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Clintonia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2000, "Scania", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2600, "Thurso", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1800, "Gartavon", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Stratford", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Tuva", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Frederika Lensen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Royal Sceptre", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2700, "Vingaland", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3200, "Hatasu", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2100, "Bluefields", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Blairlogie", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3700, "Kyleglen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Lehigh", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Navarino", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Firby", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Bassano", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Ashby", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1100, "Viking", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4000, "Aviemore", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "Thirlby", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Empire Barracuda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Broompark", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Kafirlstan", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2000, "Daphne", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Cassequel", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Condylis", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1000, "Truro", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2700, "Tweed", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Annavore", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Balladier", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2700, "Akenside", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Esmond", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3000, "Thorstrand", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1600, "Trolla", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Stonepool", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2600, "Bengore Head", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3000, "Culebra", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Shaftesbury", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Winkleigh", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Starcross", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4100, "Olinda", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3300, "Arlyn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2500, "Stanholme", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Alfred Jones", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3100, "Ontario", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Aeas", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Arlington Court", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Pandias", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2400, "Torny", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2200, "Caribou", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Sliedrecht", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4000, "RioAzul", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Ogontz", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4700, "Woensdrecht", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Counsellor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3000, "Robert L Holt", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Carabulle", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1200, "Antonico", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Sheaf Mead", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Soloy", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Goncalves Dias", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Bancrest", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2100, "Merisaar", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Vigrid", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Willimantic", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4200, "Marcrest", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4000, "Stakesby", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Kinross", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3500, "Denmark", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Daydawn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4200, "Gro", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4400, "Nicolas Pateras", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Pontypridd", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4100, "Dayrose", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2400, "Mardinian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1300, "Erato", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1300, "Anna", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Dalcroy", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3700, "Baron Blythswod", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Kumasian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4900, "RioTercero", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2000, "SeaGlory", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3700, "Graigwen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4500, "Cape Rodney", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4600, "Leonidas M.", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2300, "Sea Venture", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1800, "Trevisa", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 1200, "Clantara", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Nordal", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3700, "Baron Dechmont", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 3800, "Scoresby", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 2100, "Spind", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 5000, "Manuela", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.SMALL_FREIGHTER, 4800, "Reedpool", ShipRegion.WORLD) }
            };
        }

        private static IList<Ship> NorthAmericaTankers()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.TANKER, 9100, "Norness", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6800, "Coimbra", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6600, "Allan Jackson", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8200, "Malay", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8100, "Empire Gern", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9100, "Diala", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9300, "Varanger", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7100, "Francis E. Powell", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "Halo", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 11300, "Montrolite", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8300, "India Arrow", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8400, "ChinaArrow", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6200, "W.L. Steed", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5300, "Republic", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10200, "W.D. Anderson", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8200, "Pan Massachusetts", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 11000, "O.A. Knudsen", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8000, "Esso Nashville", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 11400, "Atlantic Sun", ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8000, "DixieArrow", ShipRegion.NORTH_AMERICA) }
            };
        }

        private static IList<Ship> Tankers()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.TANKER, 9400, "Inverliffey", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6700, "La Brea", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 12000, "Cadillac", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6200, "Ensis", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10000, "Regent Tiger", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7500, "Pecten", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6600, "Athelbeach", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9500, "Kongsgaard", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8500, "British lnfluence", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8400, "British Farne", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6200, "Erodona", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8800, "Maasdam", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8800, "Cheyenne", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5800, "Sarita", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9300, "Franche Comte", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8700, "Malayall", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 14000, "Emile-Miguet", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9200, "Invershannon", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6600, "Fern", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8000, "Anadara", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 11000, "Arne Kjode", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10000, "Torinia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8100, "Beduin", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7500, "Bulysses", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7400, "San Alberto", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10000, "Frederick S. Fales", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5700, "Venetia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6500, "Tahchee", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5000, "Vaclite", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "British General", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8700, "Gastor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 12800, "San Florentino", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5200, "Chastine Maersk", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "Nina Borthen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "British Reliance", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8200, "T.J. Williams", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8000, "Ceronia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7100, "Davanger", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6900, "British Viscount", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6300, "Barbro", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7800, "Caroni River", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9500, "Languedoc", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8000, "Chama", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 15000, "Svend Foyn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9000, "Den Haag", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 13900, "New Sevilla", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8100, "Conus", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9600, "W.C. Teagle", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8000, "Imperial Transport", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5400, "Casanare", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5600, "Lincoln Ellsworth", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6600, "Erviken", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5700, "Daghestan", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "Scottish Maiden", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8500, "Duffield", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9800, "Barfonn", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 2600, "Leticia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5000, "Congonian", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8200, "Capulet", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9000, "Salinas", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 13000, "San Fernando", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7600, "Havbor", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8900, "Oitfield", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "T.C.White", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10000, "Italia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8800, "Appalachee", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9900, "Caledonia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9200, "Inverlee", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9000, "Eli Knudsen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 12200, "Victor Ross", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6100, "John P. Pederson", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7500, "Sagona", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 12000, "Saranac", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 5900, "British Premier", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8500, "British Security", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8100, "Darkdale", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7500, "Moerdrecht", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9000, "Charles Pratt", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8100, "Cairndale", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "British Mariner", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9000, "Athellaird", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10500, "W.B. Walker", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6900, "British Grenadier", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 11900, "Astral", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8600, "Yarraville", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10500, "A.F. Corwin", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8800, "Alfred Olsen", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8100, "San Demetrio", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 2600, "Lucretia", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10500, "E.R. Brown", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 9500, "Inversuir", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7200, "British Resource", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "Scottish Minstrel", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 7000, "Scottish Standard", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6000, "Wellfield", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 8600, "Winamac", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6800, "Athelcrest", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 6900, "British Gunner", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10700, "Pendrecht", ShipRegion.WORLD) },
                { ShipFactory.CreateShip(ShipType.TANKER, 10400, "Narragansett", ShipRegion.WORLD) }
            };
        }

        private static IList<Ship> CapitalShips()
        {
            return new List<Ship>()
            {
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 22000, "CV Ark Royal", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 29100, "BB Royal Oak", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 18600, "CV Courageous", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 10000, "CA Belfast", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 31100, "BB Barham", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 34000, "BB Nelson", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 31300, "BB Malaya", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 22600, "CV Eagle", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 12800, "CVE Avenger", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) },
                { ShipFactory.CreateShip(ShipType.CAPITAL_SHIP, 11000, "CVE Audacity", ShipRegion.WORLD & ShipRegion.NORTH_AMERICA) }
            };
        }
        #endregion METHODS
    }
}